#!/usr/bin/python

from selenium import webdriver
import memcache
import time


class User:
    def __init__(self):
        pass
    username = ""
    browser = webdriver.Chrome()
    executor_url = browser.command_executor._url
    session_id = browser.session_id

    def login(self):
        self.browser.get('https://codeforces.com/enter')
        while True:
            if self.browser.current_url == "https://codeforces.com/":
                self.executor_url = self.browser.command_executor._url
                self.session_id = self.browser.session_id
                self.browser.minimize_window()
                self.username = self.browser.find_element_by_link_text("Blog").get_attribute("href").split('/')[-1]
                break
            time.sleep(0.5)
        return


def main():
    session = User()
    session.login()
    shared = memcache.Client(['127.0.0.1:11211'], debug=0)
    shared.set('session_id', session.session_id)
    shared.set('executor_url', session.executor_url)
    shared.set('username', session.username)
    time.sleep(2)


if __name__ == "__main__":
    main()
